/**
 * The CKP building in the footer, under "Until we meet on campus" — IPSR
 * colours: lines #123A1A, mid-tones #2C7A47, body #F3F9F1, pen #2C7A47.
 *
 * Generated by scripts/campus_engraving_gen.py (656 shapes, 2105 pen strokes,
 * without the water tank). To change it, replace the source files in
 * scripts/ and run the script — don't edit the SVGs by hand.
 *
 * When the footer comes into view, the pen lines open from the entrance out to
 * both sides, the drawing fills in just behind them, and the ink fades — it
 * replays each time the footer returns to view. Each layer is split into two
 * halves whose windows slide outwards while their content slides back by the
 * same amount: only translations animate, so everything is painted once at full
 * sharpness and never repainted, on any device (campus-engraving.css).
 */

import { useEffect } from 'react';
import './campus-engraving.css';
import fillUrl from '../assets/campus-engraving-fill.webp';
import inkUrl from '../assets/campus-engraving-ink.webp';

export default function CampusEngraving({ drawn }: { drawn: boolean }) {
  // decode both images in the background as soon as the page loads, so the
  // reveal never waits on them
  useEffect(() => {
    for (const src of [fillUrl, inkUrl]) {
      const img = new Image();
      img.src = src;
      img.decode?.().catch(() => undefined);
    }
  }, []);
  // each layer in two halves, uncovered from the entrance outwards
  const halves = (src: string) =>
    (['l', 'r'] as const).map((side) => (
      <div key={side} className={`ckpc-half ${side}`}>
        <div className="ckpc-inner">
          <img className="ckpc-layer" src={src} alt="" draggable={false} decoding="async" />
        </div>
      </div>
    ));
  return (
    <div className={`ckpc-art ${drawn ? 'is-drawn' : ''}`} aria-hidden="true">
      <div className="ckpc-fill">{halves(fillUrl)}</div>
      <div className="ckpc-ink">{halves(inkUrl)}</div>
    </div>
  );
}
