"""Generates src/components/CampusEngraving.tsx — the CKPCMC building in the footer.

Source: scripts/campus_engraving.svg, a vector drawing of the building's front
elevation (filled shapes in greys, as a vectoriser produces).

What this does, and only this:
  - drops the full-canvas white background (shape 0), so the footer shows through
  - crops the canvas to the drawing
  - prints it in CMC gold: each grey becomes the matching shade between the gold
    ink (#8C6E1E, for black) and the footer's paper (#F9F5EE, for white)
  - prefixes gradient ids (ckpc-…) so they can't clash with anything on the page
  - leaves out the water tank on the roof (dome, platform and shaft), with a mask:
    its lines are carved out of the drawing's one large dark shape, so it can't be
    deleted shape by shape. The annex beside the shaft, its cap, the roof line and
    the glass tower are kept.
The path data is copied byte for byte: it is written in relative steps, so even
rounding it would make shapes drift.

Run from frontend/:  python3 scripts/campus_engraving_gen.py
To change the building, replace the SVG and run it again.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "campus_engraving.svg")
OUT = os.path.join(HERE, "..", "src", "components", "CampusEngraving.tsx")

INK = (0x8C, 0x6E, 0x1E)
PAPER = (0xF9, 0xF5, 0xEE)
VIEWBOX = (4, 199, 2036, 901)       # the drawing (10 205 2034 1094) plus a small margin

# Hidden: the water tank, in the SVG's own units (measured from the drawing).
#   dome + platform x 962-1107, y 205-332 · shaft pipes x 1000-1070, down to the
#   roof line at y 438 · the annex cap reaches x 1065 at y 360-374, so it is spared
HIDE = (
    (958, 198, 1111, 333),      # dome and platform
    (996, 326, 1063, 437.6),    # shaft (to the roof line's top edge, at y 438)
    (1063, 326, 1072, 358),     # right pipe, above the annex cap
    (1063, 374, 1072, 437.6),   # right pipe, below the annex cap
)


def gold(hexv):
    h = hexv.lstrip("#")
    h = "".join(c * 2 for c in h) if len(h) == 3 else h
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    t = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255
    return "#%02x%02x%02x" % tuple(round(i * (1 - t) + p * t) for i, p in zip(INK, PAPER))


def main():
    s = open(SRC, encoding="utf-8").read()
    grads = []
    for m in re.finditer(r'<linearGradient id="(\w+)" ([^>]*)>(.*?)</linearGradient>', s, re.S):
        attrs = dict(re.findall(r'(\w+)="([^"]*)"', m.group(2)))
        stops = "".join(
            f'<stop offset="{o}" stopColor="{gold(c)}" />'
            for o, c in re.findall(r'offset="([^"]*)" stop-color="([^"]*)"', m.group(3))
        )
        grads.append(
            f'        <linearGradient id="ckpc-{m.group(1)}" x1="{attrs["x1"]}" x2="{attrs["x2"]}" '
            f'y1="{attrs["y1"]}" y2="{attrs["y2"]}" gradientUnits="userSpaceOnUse">{stops}</linearGradient>'
        )
    shapes = []
    for i, m in enumerate(re.finditer(r"<path([^>]*)/?>", s)):
        if i == 0:
            continue                                   # the white background
        a = m.group(1)
        d = re.search(r'\sd="([^"]*)"', a).group(1)
        f = re.search(r'fill="([^"]*)"', a)
        fill = f.group(1) if f else "#000"
        fill = "url(#ckpc-" + fill[5:] if fill.startswith("url(#") else gold(fill)
        shapes.append(f'  ["{fill}", "{d}"],')
    vx, vy, vw, vh = VIEWBOX
    mask = "\n".join(
        [f'          <rect x="{vx}" y="{vy}" width="{vw}" height="{vh}" fill="#fff" />']
        + [f'          <rect x="{x1}" y="{y1}" width="{x2 - x1}" height="{round(y2 - y1, 1):g}" fill="#000" />' for x1, y1, x2, y2 in HIDE]
    )
    body = TEMPLATE.format(
        mask=mask,
        n=len(shapes),
        vb=" ".join(map(str, VIEWBOX)),
        vb_x=vx, vb_y=vy, vb_w=vw, vb_h=vh,
        grads="\n".join(grads),
        shapes="\n".join(shapes),
    )
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(body)
    print(f"wrote {os.path.relpath(OUT)}: {len(shapes)} shapes, {len(grads)} gradients")


TEMPLATE = '''/**
 * The CKPCMC building in the footer, under "Until we meet on campus": the centre
 * block and water tower, the crenellated wings and roundel towers, the flight of
 * steps with its ramps and hedges, and the oval forecourt.
 *
 * Generated by scripts/campus_engraving_gen.py from scripts/campus_engraving.svg
 * ({n} shapes, printed in CMC gold, without the water tank on the roof). To change
 * it, replace the SVG and run the script again rather than editing the data below.
 *
 * The drawing is made of filled shapes, so it is revealed rather than drawn:
 * it uncovers from the entrance outwards when the footer comes into view
 * (campus-engraving.css).
 */

import './campus-engraving.css';

// [fill, path]
const SHAPES: ReadonlyArray<readonly [string, string]> = [
{shapes}
];

export default function CampusEngraving({{ drawn }}: {{ drawn: boolean }}) {{
  return (
    <svg
      className={{`ckpc-svg ${{drawn ? 'is-drawn' : ''}}`}}
      viewBox="{vb}"
      preserveAspectRatio="xMidYMax meet"
      aria-hidden="true"
      focusable="false"
    >
      <defs>
{grads}
        {{/* everything except the water tank */}}
        <mask id="ckpc-no-tank" maskUnits="userSpaceOnUse" x="{vb_x}" y="{vb_y}" width="{vb_w}" height="{vb_h}">
{mask}
        </mask>
      </defs>
      <g mask="url(#ckpc-no-tank)">
        {{SHAPES.map(([fill, d], i) => (
          <path key={{i}} fill={{fill}} d={{d}} />
        ))}}
      </g>
    </svg>
  );
}}
'''

if __name__ == "__main__":
    main()